package com.tekzee.mallortaxiclient.constant

object ConstantLib {
    const val DRIVER_ID = "driver_id"
    const val NOTIFICAION = "notificaion"
    const val USER_DATA = "user_data"
    const val FROM = "from"
    const val FRIEND_ID = "friend_id"
    const val BOOKING_ID = "booking_id"
    const val USER_NAME = "user_name"
    const val VENUE_TYPE_SELECTED = "venue_type_selected"
    const val MUSIC_SELETED = "music_seleted"
    const val AGE_GROUP_SELECTED = "age_group_selected"
    const val AGE_FILTER_FROM_SELECTED = "age_filter_from_selected"
    const val AGE_FILTER_TILL_SELECTED = "age_filter_till_selected"
    const val DISTANCE_FILTER_FROM_SELECTED = "distance_filter_from_selected"
    const val DISTANCE_FILTER_TO_SELECTED = "distance_filter_to_selected"
    const val LANGUAGE_ID_SELECTED = "language_id_selected"
    const val USER_EMAIL = "user_email"
    const val USER_DOB = "user_dob"
    const val API_TOKEN = "api_token"
    const val ACCESS_TOKEN = "access_token"
    const val PROFILE_IMAGE = "profile_image"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val FCMTOKEN = "fcmtoken"
    const val USER_ID = "user_id"
    const val USER_AGE = "user_age"
    const val REJECTION_MESSAGE = "rejection_message"
    const val INVITE_FRIEND_COUNT = "invite_friend_count"
    const val INVITE_FRIEND = "invite_friend"
    const val IS_INVITE_FRIEND = "is_invite_friend"
    const val INVITE_MESSAGE = "invite_message"

    const val LANGUAGE_CODE= "language_code"
    const val LANGUAGE_NAME= "language_name"
    const val LANGUAGE_DATA= "language_data"
    const val DEVICETYPE= "ANDROID"
    const val PAGEURL= "pageurl"
    const val ISAGREE= "isagree"
    const val OPENMIDED_CHECKBOX= "openmided_checkbox"
    const val SPREAD_CHECKBOX= "spread_checkbox"
    const val TURNTUP_CHECKBOX= "turntup_checkbox"
    const val LICENCE_AGREEMENT_COMPLETED= "licence_agreement_completed"
    const val TERMSANDCONDITION= "https://amiggos.com/Amiggos_tek/public/uploads/static_pages/Termscondition.php"



}